### ISSUE TITLE
Suggestion and Help

### ISSUE THREAD

**Issue by VPBase** [MikeZeDev/fujitvDownloader#2]
I have a suggestion. I know how to get the scrambled pages from premium content (You might also know this of course). But the issue is to descramble those images. I guess we can't get the keys for premium content that easily (There might be some way). I wanted to talk about this in private. How can I contact you?

**Comment by lemonatez** [comment]
Is it have a method to access?

**Comment by MikeZeDev** [comment]
I am not interested, sorry.
